version: '3.8'

services:
  cmr-auth:
    build: .
    container_name: cmr-auth
    restart: always
    expose:
      - "8443"
    networks:
      - proxy-network
      
networks:
  proxy-network:
    external: true