version: '3.8'

services:
  cmr-auth:
    build: .
    container_name: cmr-auth
    restart: always
    ports:
      - "9000:9000"
    networks:
      - shared-network
      
networks:
  shared-network:
    external: true
