spring.application.name=restaurantesAuthServer

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=cm_restaurantes;integratedSecurity=false;TrustServerCertificate=true
spring.datasource.url=jdbc:sqlserver://192.168.1.109:1433;databaseName=cm_restaurantes;integratedSecurity=false;TrustServerCertificate=true
spring.datasource.username=cmpayapp
#spring.datasource.password=P3g2o22cmp4y
spring.datasource.password=U1ErHciSfkJ62nBguZEiU22PaTmNeyoEnNFezbT+pKr8nyWm4vjNMw==
#conexion a DB QA
#spring.datasource.url=jdbc:sqlserver://192.168.2.28:34433;databaseName=cm_restaurantes;integratedSecurity=false;TrustServerCertificate=true
#spring.datasource.username=cmpayapp
#spring.datasource.password=lhhFsRBJIrYgYy2WAf+YLQjBLuqOug9RdK05KOErm8CmdIlPaC9gvQ==

#conexion a DB desarrollo
#spring.datasource.url=jdbc:sqlserver://192.168.2.28:34433;databaseName=cm_restaurantes_dev;integratedSecurity=false;TrustServerCertificate=true
#spring.datasource.username=cmpayapp
#spring.datasource.password=lhhFsRBJIrYgYy2WAf+YLQjBLuqOug9RdK05KOErm8CmdIlPaC9gvQ==

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.porperties.format_sql=true

#server.port=5505
spring.thymeleaf.encoding=UTF-8
spring.messages.encoding=UTF-8

logging.level.root=INFO
logging.level.org.springframework=INFO
#logging.level.org.springframework.web=INFO
logging.level.org.springframework.web=TRACE
#logging.level.org.springframework.security=INFO
logging.level.org.springframework.security=TRACE
#logging.level.org.springframework.security.oauth2=INFO
logging.level.org.springframework.security.oauth2=TRACE
logging.level.org.springframework.security.web.FilterChangeProxy=DEBUG
logging.level.org.springframework.security.web.filter=DEBUG
logging.file.name=./logs/autServer.log

logging.level.org.apache.coyote.http11=DEBUG
logging.level.org.apache.tomcat.util.net=DEBUG

server.error.include-exception=true
server.error.include-message=always
server.error.whitelabel.enabled=false

spring.authorizationserver.client-id=lealtad-client
spring.authorizationserver.redirect-uri=com.praxis.cmrewards://oauth/callback
spring.authorizationserver.logout-uri=com.praxis.cmrewards://oauth/logout

spring.authorizationserver.client-idCmpay=lealtad-clientCmpay
#spring.authorizationserver.client-secretCmpay=5c13222c84942f0e53fa331f3cbcdffae6a1f75e672f35728959af3a010ae4ad
spring.authorizationserver.client-secretCmpay=3e21240bf8a1feda0091e750b2ae30653a3e065194a8f3fefb8a4550060dd7a7
#conexion a servidor QA
spring.authorizationserver.redirect-uri-aut=https://189.206.227.231:5500/authorized
#conexion a servidor de desarrollo
#spring.authorizationserver.redirect-uri-aut=http://192.168.2.31:5500/authorized
#conexion local pruebas
#spring.authorizationserver.redirect-uri-aut=http://127.0.0.1:5500/authorized


server.port=8443
server.ssl.key-store=classpath:server.p12
server.ssl.key-store-password=secreto
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=rewardsauth