spring.application.name=restaurantesAuthServer

spring.datasource.sqlserver.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.url=jdbc:sqlserver://cmr-auth-db:1433;databaseName=cm_restaurantes;integratedSecurity=false;TrustServerCertificate=true
#docker de pruebas servidor YAMA
#spring.datasource.sqlserver.url=jdbc:sqlserver://192.168.1.109:1433;databaseName=cm_restaurantes;integratedSecurity=false;TrustServerCertificate=true
#spring.datasource.sqlserver.username=cmpayapp
#spring.datasource.sqlserver.password=U1ErHciSfkJ62nBguZEiU22PaTmNeyoEnNFezbT+pKr8nyWm4vjNMw==

#spring.datasource.mysql.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.mysql.url=jdbc:mysql://192.168.1.109:3306/qa_rewards_auth?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
#spring.datasource.mysql.username=admin
#spring.datasource.mysql.password=lWn+u5adr5K/+9dnBgcnG/Gp9Q+trCtxHPQo5HPMGZJwyuNYVXmHJQ==
#contraseña en claro
#spring.datasource.password=P3g2o22cmp4y

#conexión a QA - generado por Mari
#spring.datasource.url=jdbc:sqlserver://201.163.153.19:34433;databaseName=lealtad;integratedSecurity=false;TrustServerCertificate=true
#spring.datasource.username=lealtad
#spring.datasource.password=Gp4tyZrpg7IO58VYME1WdpriEu1FDMVfrWVdc9+T80tjEJuKWGddwjB3GiW1AGPW
#contraseña en claro
#spring.datasource.password=hatOXjzTHVtrLK02XhTl

#conexion a DB QA
#spring.datasource.sqlserver.url=jdbc:sqlserver://201.163.153.19:34433;databaseName=cm_restaurantes;integratedSecurity=false;TrustServerCertificate=true
#spring.datasource.sqlserver.username=cmpayapp
#spring.datasource.sqlserver.password=lhhFsRBJIrYgYy2WAf+YLQjBLuqOug9RdK05KOErm8CmdIlPaC9gvQ==

#conexion a DBs locales
#spring.datasource.url=jdbc:sqlserver://cmr-auth-db:1433;databaseName=cm_restaurantes_dev;integratedSecurity=false;TrustServerCertificate=true
spring.datasource.username=cmpayapp
spring.datasource.password=lhhFsRBJIrYgYy2WAf+YLQjBLuqOug9RdK05KOErm8CmdIlPaC9gvQ==
spring.datasource.sqlserver.url=jdbc:sqlserver://192.168.1.29:1433;databaseName=cm_restaurantes;integratedSecurity=false;TrustServerCertificate=true
spring.datasource.sqlserver.username=cmpayapp
spring.datasource.sqlserver.password=U1ErHciSfkJ62nBguZEiU22PaTmNeyoEnNFezbT+pKr8nyWm4vjNMw==
spring.datasource.mysql.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.mysql.url=jdbc:mysql://192.168.1.29:3306/qa_rewards_auth?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
spring.datasource.mysql.username=admin
spring.datasource.mysql.password=lWn+u5adr5K/+9dnBgcnG/Gp9Q+trCtxHPQo5HPMGZJwyuNYVXmHJQ==

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO

server.address=0.0.0.0
server.port=9000
spring.thymeleaf.encoding=UTF-8
spring.messages.encoding=UTF-8

#logging.level.root=INFO
logging.level.com.praxis.authentication=INFO
logging.level.com.praxis.authentication.configuration.RequestLoggingFilter=DEBUG
logging.level.org.springframework=WARN
#logging.level.org.springframework.web=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
#logging.level.org.springframework.security=INFO
logging.level.org.springframework.security=WARN
#logging.level.org.springframework.security.oauth2=INFO
logging.level.org.springframework.security.oauth2=WARN
logging.level.org.springframework.security.web.FilterChangeProxy=WARN
logging.level.org.springframework.security.web.filter=WARN
logging.level.org.hibernate=ERROR
logging.file.name=./logs/autServer.log

logging.level.org.apache.coyote.http11=DEBUG
logging.level.org.apache.tomcat.util.net=DEBUG

server.error.include-exception=true
server.error.include-message=always
server.error.whitelabel.enabled=false

spring.authorizationserver.client-id=lealtad-client
spring.authorizationserver.redirect-uri=com.praxis.cobromovilrewards://oauth/callback
spring.authorizationserver.logout-uri=com.praxis.cobromovilrewards://oauth/logout

spring.authorizationserver.client-idAdmin=lealtad-clientAdmin

spring.authorizationserver.client-idCmpay=lealtad-clientCmpay
#spring.authorizationserver.client-secretCmpay=5c13222c84942f0e53fa331f3cbcdffae6a1f75e672f35728959af3a010ae4ad
spring.authorizationserver.client-secretCmpay=3e21240bf8a1feda0091e750b2ae30653a3e065194a8f3fefb8a4550060dd7a7
#conexion a servidor QA
spring.authorizationserver.redirect-uri-aut=https://189.206.227.231:5500/authorized
#conexion a servidor de desarrollo
#spring.authorizationserver.redirect-uri-aut=http://192.168.2.31:5500/authorized
#conexion local pruebas
#spring.authorizationserver.redirect-uri-aut=http://127.0.0.1:5500/authorized

#server.port=8443
#server.ssl.key-store=classpath:server.p12
#server.ssl.key-store-password=secreto
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=rewardsauth

forward-headers-strategy: native

# Configuración de sesión y cookies
server.servlet.session.tracking-modes=cookie
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=None
server.servlet.session.cookie.path=/
server.servlet.session.timeout=30m

# Configuración del proxy
server.forward-headers-strategy=native
