spring.application.name=restaurantesAuthServer

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#conexion a DB QA
spring.datasource.url=jdbc:sqlserver://192.168.2.28:34433;databaseName=cm_restaurantes;integratedSecurity=false;TrustServerCertificate=true
#spring.datasource.username=restaurantesapp
spring.datasource.username=cmpayapp
#spring.datasource.password=oI9gzo5tVz1LaODK+0uHczEClfUkxA+cwEuQLPB5ye5iIKYzWNPUOCaKXtJDTW4t
spring.datasource.password=lhhFsRBJIrYgYy2WAf+YLQjBLuqOug9RdK05KOErm8CmdIlPaC9gvQ==
#conexion a DB desarrollo
#spring.datasource.url=jdbc:sqlserver://192.168.2.28:34433;databaseName=cm_restaurantes_dev;integratedSecurity=false;TrustServerCertificate=true
#spring.datasource.username=cmpayapp
#spring.datasource.password=lhhFsRBJIrYgYy2WAf+YLQjBLuqOug9RdK05KOErm8CmdIlPaC9gvQ==

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.porperties.format_sql=true

server.port=5505
spring.thymeleaf.encoding=UTF-8
spring.messages.encoding=UTF-8

logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.oauth2=INFO
logging.level.org.springframework.security.web.FilterChangeProxy=INFO
logging.level.org.springframework.security.web.filter=INFO
logging.file.name=./logs/autServer.log

server.error.include-exception=true
server.error.include-message=always
server.error.whitelabel.enabled=false

spring.authorizationserver.client-id=restaurantes-client
spring.authorizationserver.redirect-uri=cmpay://oauth/callback
spring.authorizationserver.logout-uri=cmpay://oauth/logout
spring.authorizationserver.client-idCmpay=restaurantes-clientCmpay
spring.authorizationserver.client-secretCmpay=5c13222c84942f0e53fa331f3cbcdffae6a1f75e672f35728959af3a010ae4ad
#conexion a servidor QA
spring.authorizationserver.redirect-uri-aut=http://192.168.2.29:5500/authorized
#conexion a servidor de desarrollo
#spring.authorizationserver.redirect-uri-aut=http://192.168.2.31:5500/authorized
#conexion local pruebas
#spring.authorizationserver.redirect-uri-aut=http://127.0.0.1:5500/authorized




